[package]
name = "disc_bot"
version = "0.1.0"
authors = ["Alec Goncharow <Alec.Goncharow@gmail.com>"]

[dependencies]
rand = "*"
serenity = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
artifact_serde = "0.3.0"
artifact_lib = "0.2"
lazy_static = "1.2.0"
